on: 
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose The environment: "
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
        
jobs:
  handle-incident:
    runs-on: ubuntu-latest
    steps:
      - name: Print env details
        run: echo "app deployed to ${{inputs.environment}}"
         
    
