name: Test-workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Enter The Environment: "
        default: "stagging"
        required: true
        type: choice
        options:
          - stagging
          -  production
jobs:
  hybrid-job:
    runs-on: ubuntu-latest
    steps:
    - name: run script on VM
      run: echo "this step run on Ubuntu VM"
    - name: run a script on docker cont 
      uses: docker://alpine:latest
      with:
        enterypoint: /bin/sh
        args: -c "echo 'this script runs on docker cont'"
    - name: run another script on VM
      run: echo "script runs another time on VM"
         
    
 
        
